alluxiacademy/alluxiacademy/urls.py
from django.contrib import admin
from django.urls import path, include
import django.contrib.staticfiles.urls as urls
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing.urls')),
]

urlpatterns += urls.staticfiles_urlpatterns()
urlpatterns += urls.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

alluxiacademy/landing/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.get_course, name='index'),
    path('cursos/<str:slug>', views.get_course, name='get_course'),    
]

alluxiacademy/landing/models.py
from django.db import models
from django.core.validators import FileExtensionValidator
from autoslug import AutoSlugField
from django.utils.text import slugify

class Status(models.Model):    
    name = models.CharField(max_length=100)   
    description = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Status"

class Career(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=200)
    institution = models.CharField(max_length=200)
    status = models.ForeignKey(Status, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

class Instructor(models.Model):
    name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100, default="")
    last_second_name = models.CharField(max_length=100, default="", blank=True)
    age = models.IntegerField()
    title = models.CharField(max_length=200)
    current_job = models.CharField(max_length=200)
    work_history = models.CharField(max_length=1000, default="")
    linkedin_account_link = models.CharField(max_length=150, blank=True)
    github_account_link = models.CharField(max_length=150, default="", blank=True)
    photo = models.FileField(null=True, verbose_name='Foto instructor')
    careers = models.ManyToManyField(Career, blank=True)
    status = models.ForeignKey(Status, on_delete=models.CASCADE)
    slug = AutoSlugField(null=True, unique= True, populate_from='name', default=None)

    def __str__(self):
        return self.name + " " + self.last_name

    def save(self, *args, **kwargs):
        names = [slugify(self.name), slugify(self.last_name)]
        if(self.last_second_name != ""):
            names.append(self.last_second_name)
        self.slug = '-'.join(names)
        super(Instructor, self).save(*args, **kwargs)

class Course(models.Model):
    title = models.CharField(max_length=500)
    advertising_phrase = models.CharField(max_length=500, default="")
    description = models.CharField(max_length=750)
    summary = models.CharField(max_length=750, default="")
    duration_in_weeks = models.IntegerField()
    location = models.CharField(max_length=200)
    start_date = models.DateField(null=True,blank=True)
    start_hour = models.DateTimeField()
    finish_hour = models.DateTimeField()
    instructor = models.ForeignKey(Instructor, on_delete=models.CASCADE)
    price = models.FloatField(default=0)
    status = models.ForeignKey(Status, on_delete=models.CASCADE)
    featured = models.BooleanField(default=False)
    slug = AutoSlugField(null=True, unique= True, populate_from='title', default=None)

    def __str__(self):
        return self.title 

class Phase(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=200, blank=True)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    status = models.ForeignKey(Status, on_delete=models.CASCADE)

    def __str__(self):
        return self.course.title  + "-" + self.name
    
class Topic(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=100, blank=True)    
    phase = models.ForeignKey(Phase, on_delete=models.CASCADE)

    def __str__(self):
        return self.phase.course.title + " - " + self.phase.name + " - "+ self.name

alluxiacademy/landing/views.py
import sweetify
from django.core.mail import send_mail
from django.shortcuts import render
from django.template.loader import render_to_string
from .models import Course
from django.conf import settings
import pdb
import requests

def send_mail_wrapper(title, template, context, recipients):
    html_message = render_to_string(
        template, context)
    send_mail(title,
              html_message,
              '',
              recipients,
              html_message=html_message,
              fail_silently=False)


def _submit_form(request):
    try:
        email = request.POST.get('email')
        content = request.POST.get('content')
        context = {
            'email': email,
            'content': content,
        }
        send_mail_wrapper('Contacto Alluxi Academy',
                          'landing/contact_email.html',
                          context, ['hola@alluxi.mx'])

        sweetify.success(request, '¡Gracias por tu mensaje! Nos pondremos en contacto contigo a la brevedad.')
    except Exception as e:
        sweetify.error(request, 'Error: ' + str(e))

def image_url_fixed(url_to_check, request):
    url_fixed = "https://via.placeholder.com/150"

    if (url_to_check == "" or url_to_check == None):
        return url_fixed

    domain = request.build_absolute_uri('/')[:-1]    
    response = requests.get(domain+url_to_check)

    if (response.status_code == 200):
        return url_to_check 
    return url_fixed

def get_course(request, slug = ""):
    if request.method == 'POST':
        _submit_form(request)

    if slug == "":
        course = Course.objects.get(featured=True)
    else:
        course = Course.objects.get(slug=slug)

    courses = Course.objects.all().order_by('-id')[:3]
    image_url  = image_url_fixed(course.instructor.photo.url, request)
    context = {'course': course, 'courses': courses, 'image_url_fixed': image_url}
          
    return render(request, 'landing/index-course.html', context)

alluxiacademy/landing/templates/landing/contact_email.html
<h3>Nuevo Contacto Alluxi Academy</h3>
<p>Email: {{ email }}</p>
<p>Contenido: {{ content }}</p>

alluxiacademy/landing/templates/landing/index-course.html
{% extends './base.html' %}

{% load static %}

{% block header %}
<header class="masthead text-white">
    <div class="masthead-content">
        <div class="container">
            <h1 class="masthead-heading mb-0 Build-Your-First-And">{{course.title}}</h1>
            <h2 class="masthead-subheading mb-0 mt-20 Learn-Android-App-De">{{course.advertising_phrase}}</h2>
            <a href="https://alluxi.typeform.com/to/E7QnHL">
                <button type="button" class="btn btn-primary BG mt-20">MÁS INFORMACIÓN</button>
            </a>
        </div>
    </div>
</header>
{% endblock %}

{% block subheader %}
<section>
    <div class="container">
        <div class="row align-items-center ptb-50">
            <p class="About-this-course col-lg-12">Sobre este curso</p>
            <div class="col-lg-6 Lorem-ipsum-dolor-si">
                <p>
                    {{course.description}}
                </p>
                <p class="syl-title">
                    Se llevará a cabo en <br/> <a href="https://goo.gl/maps/U4TVNmErnUC2">{{course.location}}</a>
                </p>
            </div>
            <div class="col-lg-6">
                <div class="row">
                    <div class="col-lg-6">
                        <p class="title"><img src="{% static 'img/ic-method-check.png' %}">Coaches profesionales</p>
                    </div>
                    <div class="col-lg-6">
                        <p class="title"><img src="{% static 'img/ic-method-check.png' %}">Orientación personal</p>
                    </div>
                    <div class="col-lg-6">
                        <p class="title"><img src="{% static 'img/ic-method-check.png' %}">Certificación del curso</p>
                    </div>
                    <div class="col-lg-6">
                        <p class="title"><img src="{% static 'img/ic-method-check.png' %}">Desarrollo personal</p>
                    </div>
                    <div class="col-lg-6">
                        <p class="title"><img src="{% static 'img/ic-method-check.png' %}">Nivel básico/intermedio</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block details %}
<section>
    <div class="container">
        <div class="row align-items-center ptb-50">
            <p class="Course-Information col-lg-12">Información del Curso</p>
            <div class="col-lg-12 pt-45">
                <div class="row">
                    <div class="col-lg-3 text-center">
                        <img src="{% static 'img/img-info-venue.png' %}">
                        <p class="blue-title">Sede</p>
                        <p class="Information">El curso se llevará a cabo en {{course.location}}</p>
                    </div>
                    <div class="col-lg-3 text-center">
                        <img src="{% static 'img/img-info-date.png' %}">
                        <p class="blue-title">Fecha</p>
                        <p class="Information">
                            {%if course.start_date == None %}
                                Iniciaremos el curso próximamente 
                            {% else %}
                                Iniciaremos el curso el {{course.start_date|date:'d-m-Y'}}
                            {% endif %}
                        
                        </p>
                    </div>
                    <div class="col-lg-3 text-center">
                        <img src="{% static 'img/img-info-timeline.png' %}">
                        <p class="blue-title">Duración</p>
                        <p class="Information">La duración del curso es de {{course.duration_in_weeks}} semanas</p>
                    </div>
                    <div class="col-lg-3 text-center">
                        <img src="{% static 'img/img-info-schedules.png' %}">
                        <p class="blue-title">Horario</p>
                        <p class="Information">El horario del curso es de {{course.start_hour.hour}} a {{course.finish_hour.hour}}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block subjects %}
<section>
    <div class="container">
        <div class="row align-items-center ptb-50">

            <div class="col-lg-3 Lorem-ipsum-dolor-si text-center">
                <p class="About-this-course col-lg-12">Instructor</p>
                <img class="Profile-Pic" src="{{  image_url_fixed  }}">
                <p class="Name pt-30">{{course.instructor.name}} {{course.instructor.last_name}}</p>
                <p class="Job-Title">{{course.instructor.title}}</p>
                <div class="row social pt-30">
                    {%if course.instructor.linkedin_account_link  %}
                        <a href="{{course.instructor.linkedin_account_link}}"><img class="px-15"
                                                                 src="{% static 'img/img-social-linkedin.png' %}"></a>
                    {% endif %}
                    {%if course.instructor.github_account_link  %}
                        <a href="{{course.instructor.github_account_link}}"><img class="px-15"
                                                                                              src="{% static 'img/img-social-github.png' %}"></a>
                    {% endif %}
                </div>
                <p class="pt-30 text-left">
                    {{course.instructor.work_history}}
                </p>
            </div>
            <div class="col-lg-9">
                <p class="About-this-course col-lg-12">Temario</p>
                <div class="accordion" id="accordionSyllabus">

                {% for phase in course.phase_set.all %}
                    <div class="card">
                        <div class="card-header" id="headingOne">
                            <h2 class="mb-0">                                                       
                                <button class="btn btn-link syl-title" 
                                        type="button" 
                                        data-toggle="collapse"
                                        data-target="#collapse{{forloop.counter}}"                                         
                                        aria-expanded="True"                                         
                                        aria-controls="collapse{{forloop.counter}}">
                                    {{phase.name}}
                                </button>                                
                            </h2>
                        </div>
                        {%if forloop.counter == 1 %}  
                        <div id="collapse{{forloop.counter}}" class="collapse show" aria-labelledby="heading{{forloop.counter}}"
                             data-parent="#accordionSyllabus">
                            <div class="card-body Information">
                                <ul>
                                   {% for topic in phase.topic_set.all %}
                                     <li>{{topic.name}}</li>
                                   {% endfor %}
                                </ul>
                            </div>
                        </div>
                        {% else %}
                        <div id="collapse{{forloop.counter}}" class="collapse" aria-labelledby="heading{{forloop.counter}}"
                            data-parent="#accordionSyllabus">
                            <div class="card-body Information">
                                <ul>
                                {% for topic in phase.topic_set.all %}
                                    <li>{{topic.name}}</li>
                                {% endfor %}
                                </ul>
                            </div>
                        </div>
                        {% endif %}
                    </div>
                {% endfor %}
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block paypal %}
<section class="bg-primary">
    <div class="container">
        <div class="row align-items-center ptb-50">
            <div class="col-lg-6 Take-this-course-content">
                <p class="Take-this-course col-lg-12">¡Inscríbete ahora!</p>
                <p>
                    Una vez que tu pago haya sido confirmado te enviaremos un correo de confirmación con detalles
                    necesarios para que inicies a programar como todo un profesional.
                </p>
            </div>
            <div class="col-lg-6">
                <div class="payment-BG">
                    <p class="blue-title">PYTHON CRASH COURSE</p>
                    <p class="price">${{course.price|floatformat:-2}} MXN + IVA</p>
                    <p class="Information text-center">Pago Único</p>
                    <hr/>

                    <div class="row">
                        <div class="col-lg-6">
                            <p class="pay-title"><img src="{% static 'img/ic-method-check.png' %}">Coaches profesionales
                            </p>
                        </div>
                        <div class="col-lg-6">
                            <p class="pay-title"><img src="{% static 'img/ic-method-check.png' %}">Orientación personal
                            </p>
                        </div>
                        <div class="col-lg-6">
                            <p class="pay-title"><img src="{% static 'img/ic-method-check.png' %}">Certificación del
                                                                                                   curso</p>
                        </div>
                        <div class="col-lg-6">
                            <p class="pay-title"><img src="{% static 'img/ic-method-check.png' %}">Desarrollo personal
                            </p>
                        </div>
                        <div class="col-lg-6">
                            <p class="pay-title"><img src="{% static 'img/ic-method-check.png' %}">Nivel
                                                                                                   básico/intermedio</p>
                        </div>
                    </div>
                    <div class="text-center">
                        <div type="button" id="paypal-button-container"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}